#!/bin/bash
b=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
c=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
d=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
e=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
f=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
g=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
h=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
i=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
j=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
k=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
l=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
m=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
n=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
o=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
p=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
q=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
r=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
s=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
t=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
u=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
v=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
w=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
x=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
y=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
z=$(gcc *.c && arg=$(python3 rando.py 500); ./a.out $arg | awk '{print $3}')
sum=$(echo "$b + $c + $d + $e + $f + $g + $h + $i + $j + $k + $l + $m + $n + $o + $p + $q + $r + $s + $t + $u + $v + $w + $x + $y + $z" | bc)
avg=$(echo "$sum / 25" | bc)
printf "$avg\n"
